http://localhost:3003/api
GET /blogs

http://localhost:3003/api
POST /blogs
{
  "title":"blogamongus",
  "author":"BUttNuster",
  "url":"localhost",
  "likes":10
}


http://localhost:3003/api
GET /

http://localhost:3003/api
PUT /blogs/60bb7bc2c5a81a2b75d3745a
{
        "likes":10
}
