http://localhost:3003/api
GET /blogs

http://localhost:3003/api
Authorization:bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBvb3B1aW51IiwiaWQiOiI2MGMyNDE5YTgxMTlkZjAyZDM0OWUyMTQiLCJpYXQiOjE2MjMzNDY0NzB9.E8UfQtjXyDztyP1GJKa5tCXA23pInM5sdL2B6cfoq6
Content-Type: application/json
POST /blogs
{
  "title":"blogamongus",
  "author":"BUttNuster",
  "url":"localhost",
  "likes":10
}


http://localhost:3003/api
GET /

http://localhost:3003/api
PUT /blogs/60bb7bc2c5a81a2b75d3745a
{
        "likes":10
}
