http://localhost:3001/api
GET /persons

http://localhost:3001/api
GET /info


http://localhost:3001/api
GET /persons/5

http://localhost:3001/api
DELETE /persons/60b75170ead21a224ff19af4

http://localhost:3001/api
# Content-Type: application/json; charset=utf-8
POST /persons
{
    "name": "poopu inu",
    "number": "23-14-1223132"
}


http://localhost:3001/api
PUT /persons/60b75593429e12290359992a
{
    "name": "poopu inu",
    "number": "23-14-1223132"
}
